version: '3.8' 

services:
  netman_frontend_image:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netman_frontend
    image: johedotcom/netman-frontend-repository:latest
    ports:
      - "4030:80"
    restart: always